steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['config', 'set', 'project', 'ppel-co-in']
  
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instance-templates', 'create', 'gcpp-template',
         '--machine-type', 'e2-medium',
         '--image-family', 'rhel-8',
         '--image-project', 'rhel-cloud',
         '--boot-disk-size', '20GB',
         '--boot-disk-type', 'pd-ssd']
