steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['config', 'set', 'project', 'ppel-co-in']
  
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instance-templates', 'create', 'gcpp2-template',
         '--machine-type', 'e2-medium',
         '--image-family', 'rhel-8',
         '--image-project', 'rhel-cloud',
         '--boot-disk-size', '20GB',
         '--boot-disk-type', 'pd-ssd']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'create', 'my-vm-instance',
         '--source-instance-template', 'gcpp2-template',
         '--zone', 'us-central1-a']
