steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['config', 'set', 'project', 'ppel-co-in']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'instance-templates'
    - 'describe'
    - 'gcpp-template'
    - '--format=json'
    - '--region=us-central1'
  id: 'get-template-info'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      EXISTING_VERSION=$(cat $(dirname $0)/../$BUILD_ID.json | jq '.versions[-1].name' | sed 's/v//')
      NEW_VERSION=$((EXISTING_VERSION + 1))
      echo $NEW_VERSION > $(dirname $0)/../new_version.txt

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'instance-templates'
    - 'add-version'
    - 'gcpp-template'
    - '--source-instance-template=gcpp-template'
    - '--template-version=$(cat $(dirname $0)/../new_version.txt)'
    - '--region=us-central1'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'instances'
    - 'create'
    - 'my-vm-instance'
    - '--source-instance-template=gcpp-template'
    - '--zone=us-central1-a'
