steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ppel-co-in/Dockerfile:latest', '.']

# Step 2: Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ppel-co-in/Dockerfile:latest']

# Step 3: Deploy the Docker image to Google Compute Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'instances'
    - 'create'
    - 'my-vm-instance'
    - '--image'
    - 'gcr.io/ppel-co-in/Dockerfile:latest'
    - '--machine-type'
    - 'e2-medium'
    - '--zone'
    - 'us-central1-a'
    # Add additional flags if needed, e.g., tags, labels, etc.
    - '--tags=http-server,https-server'
    # - '--labels=env=production'

# Additional steps, if needed
# ...
