name: Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: rhel8

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    - name: Deploy to GCE
      run: |
        for vm_ip in "${{ secrets.GCE_VM_IPS_SPLITTED }}"; do
          scp -i ~/.ssh/id_rsa -r . user@$35.200.140.235:/path/on/gce/vm
          ssh -i ~/.ssh/id_rsa user@$35.200.140.235 '/path/on/gce/vm/deploy.sh'
        done

