name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

#      - name: Build and Upload to Google Cloud Storage
#        run: |
#          # Set your bucket name and desired destination path
#          BUCKET_NAME="artifacts.ppel-co-in.appspot.com"
#          DESTINATION_PATH="artifacts.ppel-co-in.appspot.com/containers/"

          # Use gsutil to recursively copy files to Google Cloud Storage
#          gsutil -m cp -r ./* gs://${BUCKET_NAME}/${DESTINATION_PATH}
     
      - name: Deploy to GCE
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCE_INSTANCE_NAME: "test"
          GCE_ZONE: "asia-south1-c"
        run: |
          gcloud config set project "$PROJECT_ID"

          # Copy your application files to GCE VM using SCP
          gcloud compute scp --recurse ./* ${GCE_INSTANCE_NAME}:~/var/www/html/ --zone=${GCE_ZONE}

          # SSH into GCE VM and restart Apache
          gcloud compute ssh ${GCE_INSTANCE_NAME} --zone=${GCE_ZONE} --command="sudo systemctl restart apache2"
