name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '295.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Test
        run: |
          # Add your build and test commands here

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to GCE
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCE_INSTANCE_NAME: "test"
          GCE_ZONE: "asia-south1-c"
        run: |
          # Authenticate with Google Cloud
          echo "$SA_KEY" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project "$PROJECT_ID"

          # Copy your application files to GCE VM using SCP
          scp -i gcp-key.json -o StrictHostKeyChecking=no -r /index.html/* \
              insphere_rajat@${GCE_INSTANCE_NAME}:~/var/www/html/index.html

          # SSH into GCE VM and restart Apache
          ssh -i gcp-key.json -o StrictHostKeyChecking=no \
              insphere_rajat@${GCE_INSTANCE_NAME} \
              "sudo systemctl restart apache2"
